### ISSUE TITLE
Repos/Binaries/Installation Instruction for openSUSE

### ISSUE THREAD

**Issue by Dyrimon** [ProtonVPN/linux-app#1]
Hi, I'm facing problems installing the .rpm file for openSUSE Tumbleweed. I've separately installed the dependenciesfor openSUSE, namely python3-dialog and dbus-x11, but it still doesn't work. ProtonVPN cli and GUI gets installed but doesn't run when invoked.

**Comment by calexandru2018** [comment]
Hey @Dyrimon 

OpenSUSE is currently not officially supported.
