### ISSUE TITLE
reproducible builds

### ISSUE THREAD

**Issue by lzunsec** [ProtonVPN/linux-app#10]
I'm not very satisfied with the installation method on Ubuntu. The deb is just for adding the proton vpn repo
 I'd prefer to do a reproducible build so I could install proton vpn on my computer.

**Comment by calexandru2018** [comment]
Hey @lzunsec 👋🏻 

Could you be more specific with what you mean ?

**Comment by parrotx-proton** [comment]
Do you mean for automation you need a static url that always points to the latest .deb file?
That anyways can be a good to have @calexandru2018 even if its not OP's primary requirement

**Comment by calexandru2018** [comment]
I'm closing this issue.
