### ISSUE TITLE
OpenWRT with ProtoVPN Upload Instance Bug

### ISSUE THREAD

**Issue by big-c-note** [ProtonVPN/linux-app#11]
Forgive me in advance, this issue is not related to the linux-app. This is related to:
https://protonvpn.com/support/how-to-set-up-protonvpn-on-openwrt-routers/

It might be specific to OpenWRT, not protonvpn

If you wouldn't mind pointing me in the direction of a more appropriate place to post this issue, please do, otherwise here we go.

Wanted to post in case someone else has this issue.

1) For instruction number two, downloading the config and uploading to openwrt.

> Log in to your ProtonVPN account and click the Downloads category. You can download the desired configuration files by selecting the Router option.

> Then, go back to Openvpn and scroll down to the OVPN configuration file upload section. Browse (1) and get the desired configuration file that you have just downloaded. Give it a name (2) and upload it (3).

Although the file downloaded correctly, when uploading into openwrt line 41 becomes malformed.

Expected line 41 (also how it downloads from protonvpn)
```
proto udp
remote ...
```

After uploading to OpenWRT
```
proto udpremote ...
```

After I ssh into the router and run `logread` I could see that the uploaded file was malformed. I added a newline, and I was good to go.

**Comment by guandalf** [comment]
It may be a browser issue. Have you tried to repeat the whole operation with a different one?
If this does not help, feel free to contact our CS: https://protonvpn.com/support-form

**Comment by big-c-note** [comment]
I think I was on Brave. When I download another configuration I'll try to remember to try a different browser as well. Thanks

**Comment by calexandru2018** [comment]
Closing issue as it was answered and is not directly relevant for the app.
