### ISSUE TITLE
Window icons not visible with custom themes

### ISSUE THREAD

**Issue by OMGChase** [ProtonVPN/linux-app#16]
Hello.

I seem to be having issues with the icons on the window borders not showing up with certain 'Controls' themes on Linux Mint. Even stock themes that ship with Linux Mint. If I click where the icons should be, they act as if they are there and function as if I were clicking on them.

ProtonVPN is the only app that has this issue which makes be believe it isn't something wrong with themes, but how ProtonVPN displays the icons(?)

See below screenshots:

With no icons:
![noIcons](https://i.imgur.com/t66FTr5.png)

With icons - different theme:
![noIcons](https://i.imgur.com/nrg7u33.png)\

Theme that shows icons: Adwaita
Theme that doesn't: Mint-Y-Dark-Aqua

I will see if I can look through the theme's data and see if I can pin-point the culprit, but again, the ProtonVPN app is the only application that seems to have this bug.

Thanks for taking the time to create a GUI for Linux, really do appreacite your efforts. My only gripe with Linux is having to do everything through CLI, so a GUI is really a breath of fresh air.

**Comment by calexandru2018** [comment]
Hey @OMGChase 

Thank you for reporting this. We'll be working on fixing this as this indeed is something that should be clearly visible.

**Comment by asorel1942** [comment]
Just commenting to notify the team that I have this same issue on Manjaro KDE. If it's relevant, it appears that the official ProtonVPN is a Gnome/GTK application on KDE, and uses the application styles associated with those, rather than the KDE application style.

**Comment by OMGChase** [comment]
Hello.

This has now been fixed in latest update. Thanks!

Closing issue.
