### ISSUE TITLE
ProtonVPN autentication failed in Linux

### ISSUE THREAD

**Issue by Alex-1357** [ProtonVPN/linux-app#22]
I have successfully installed protonVPN .DEB package by converting package by Alien. ProtonVPN linux tool started but AU always failed, In background I have login to site with the same account.

![Screenshot from 2021-07-11 13 51 31](https://user-images.githubusercontent.com/86534217/125192663-b8778100-e251-11eb-8287-6f2c9b3a1f93.png)

![Screenshot from 2021-07-11 13 51 58](https://user-images.githubusercontent.com/86534217/125192669-bdd4cb80-e251-11eb-8e38-4c8101552a6a.png)

**Comment by calexandru2018** [comment]
Hey @Alex-1357 

This issue will be closed for the following reasons:
- this is the github for the official linux-app, aga GUI
- you're running the community CLI which no longer maintained by us (with the exclusion if the recent API updates): https://github.com/ProtonVPN/linux-cli-community
