### ISSUE TITLE
Can this be made to run without systemd on Devuan?

### ISSUE THREAD

**Issue by andyprough** [ProtonVPN/linux-app#24]
Just wondering if there are known steps that could be taken to run it on Devuan, which uses sysvinit by default. Are there any known work arounds to the systemd dependency? I've read that the systemd dependency is really just a convenience for the daemon and that there should be ways of getting it to work without systemd, and figured I would ask here.

The Linux community cli still works fine on Devuan, so this systemd dependency for the gui app does not block protonvpn use on Devuan.

**Comment by calexandru2018** [comment]
Hey @andyprough 

Currently there are no plans to support non-systemd machines. We could though ask directly the devuan devs in IRC or via forums: https://www.devuan.org/os/community
