### ISSUE TITLE
Lag on startup

### ISSUE THREAD

**Issue by demostanis** [ProtonVPN/linux-app#3]
There is a little lag on startup, and the main window becomes unmovable for ~5 seconds.
Probably related to this error:
```
/usr/lib/python3.9/site-packages/protonvpn_nm_lib/core/connection_backend/nm_client/nm_client_mixin.py:11: Warning: g_main_context_push_thread_default: assertion 'acquired_context' failed
  nm_client = NM.Client.new(None)
```

**Comment by calexandru2018** [comment]
Hey @demostanis 

This little "lag" has to do with the list generation, but it's something that we're looking into fixing.

**Comment by calexandru2018** [comment]
This has been fixed with the latest update.
