### ISSUE TITLE
Missing TCP/UDP switch

### ISSUE THREAD

**Issue by alexandrevicenzi** [ProtonVPN/linux-app#47]
Hi,

Is there a way to switch between TCP/UDP on the Linux app?
It defaults to UDP and some websites block UDP clients.

The only place available is in `protonvpn-cli` cmd line.

**Comment by calexandru2018** [comment]
Hey @alexandrevicenzi 

Currently no as we don't have a settings window, so you'll have to change it from the CLI at this point.
