### ISSUE TITLE
Support Fedora 35 (Python 3.10)

### ISSUE THREAD

**Issue by nunocastromartins** [ProtonVPN/linux-app#48]
Fedora 35 is currently in beta and should come out later this month shipping Python 3.10.

Attempting to install `protonvpn-gui` in Fedora 35 with `dnf install protonvpn-gui` currently results in the following error:
```
Error: 
 Problem: conflicting requests
  - nothing provides python(abi) = 3.9 needed by protonvpn-gui-0.7.2-1.noarch
  - nothing provides python(abi) = 3.9 needed by protonvpn-gui-0.7.3-2.noarch
  - nothing provides python(abi) = 3.9 needed by protonvpn-gui-1.0.0-1.noarch
  - nothing provides python(abi) = 3.9 needed by protonvpn-gui-1.0.1-1.noarch
  - nothing provides python(abi) = 3.9 needed by protonvpn-gui-1.1.0-7.noarch
  - nothing provides python(abi) = 3.9 needed by protonvpn-gui-1.1.1-1.noarch
  - nothing provides python(abi) = 3.9 needed by protonvpn-gui-1.2.0-2.noarch
  - nothing provides python(abi) = 3.9 needed by protonvpn-gui-1.3.0-7.noarch
```

It would be nice if you could publish a new version built with Python 3.10 in anticipation of the Fedora 35 release.
Thank you!

**Comment by khaytsus** [comment]
@calexandru2018 Fedora 35 was released today :)

**Comment by methane4** [comment]
Fedora 35 just got released and only protonvpn-cli has f35 support, protonvpn-gui is removed on update as a notice before the upgrade process starts states that it isnt compatible with fedora 35 as its not available in the provided repo.

cc @calexandru2018

**Comment by calexandru2018** [comment]
Hey all, we’re working on it and should have the repo for f35 available soon

**Comment by calexandru2018** [comment]
Fedora 35 support is now public, closing this ticket

**Comment by methane4** [comment]
cc @calexandru2018 
I have noticed that the tray icon isnt showing up for me anymore (and it was before). Should i open an issue?

**Comment by privilegejunkie** [comment]
@methane4 Install the app indicator support extension from here: https://extensions.gnome.org/extension/615/appindicator-support/

This fixes it for Gnome 41 which the latest Fedora uses. This fixed the issue for me.

**Comment by methane4** [comment]
> @methane4 Install the app indicator support extension from here: https://extensions.gnome.org/extension/615/appindicator-support/
> 
> This fixes it for Gnome 41 which the latest Fedora uses. This fixed the issue for me.

@privilegejunkie thats the extension i always had, not sure why it doesnt work on f35 protonvpn (other apps work fine)

**Comment by calexandru2018** [comment]
Hey @methane4 

we’re going to update soon our install instructions for the app indicator. Check the tutorial again tomorrow or after tomorrow.

**Comment by methane4** [comment]
I was able to get it working, i needed _libappindicator-gtk3_ but it wasnt needed on fedora 34 for some reason and it worked fine.
