### ISSUE TITLE
I cant start the linux app

### ISSUE THREAD

**Issue by x0d3** [ProtonVPN/linux-app#59]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------
I download and install the Linux app with the steps mentioned on the official website 'https://protonvpn.com/support/official-linux-vpn-kali/' and no errors in the installation process otherwise, the app is not even starting.
I'm using kali as a 'root' user and I created a normal user account but still got the same issue. any help, please?

**Comment by calexandru2018** [comment]
Hey @x0d3 

try to run the app from a terminal: protonvpn

**Comment by x0d3** [comment]
Hey @calexandru2018
it does not recognize the bash command protonvpn

**Comment by x0d3** [comment]
Hey @calexandru2018 
I solve this issue by uninstalling it and re-install it again and a reboot.
but I counter another issue which is not connecting to any of the available free servers provided in my free plan. can you help!?

**Comment by calexandru2018** [comment]
@x0d3 please reach out to our support team via https://protonvpn.com/support-form
