### ISSUE TITLE
Several dependencies not in the repos

### ISSUE THREAD

**Issue by telometto** [ProtonVPN/linux-app#6]
Fedora 34

Some of the deps aren't in the repos: `python3-gi` and `python3-gi-cairo` aren't in the repositories. Maybe it is a typo? What are the equivalents of these repos on fedora?

**Comment by calexandru2018** [comment]
hey @telometto 

Please take a look at the .SPEC file here: https://github.com/ProtonVPN/linux-app/blob/master/rpmbuild/SPECS/protonvpn-gui.spec

Please close the ticket once the issue is solved.

**Comment by calexandru2018** [comment]
Closing ticket due to inactivity.
