### ISSUE TITLE
Can't start newly installed app

### ISSUE THREAD

**Issue by njpaz** [ProtonVPN/linux-app#65]
I just installed the Linux client on Arch Linux using the AUR package (via `yay`), but am unable to start the app. This is what I see when I try to start it via the terminal:

```
» protonvpn
Traceback (most recent call last):
  File "/usr/bin/protonvpn", line 5, in <module>
    from protonvpn_cli.cli import main
ModuleNotFoundError: No module named 'protonvpn_cli'
```

I had installed the older CLI app almost a year ago, but had uninstalled that before installing the official Linux app.

The closest issue I could find was #61, but 1) this is a fresh install, and 2) I tried to follow the steps in that issue (including installing `python-protonvpn-nm-lib`) without success.

**Comment by calexandru2018** [comment]
Hey @njpaz 
you’ve either not removed the community cli correctly or there were some leftovers after uninstall. I would recommend to contact support.
