### ISSUE TITLE
Please provide rpm repository for fedora 36 

### ISSUE THREAD

**Issue by sbe-arg** [ProtonVPN/linux-app#70]
```bash
ProtonVPN Fedora Stable repository                                             95  B/s | 162  B     00:01    
Errors during downloading metadata for repository 'protonvpn-fedora-stable':
  - Status code: 404 for https://repo.protonvpn.com/fedora-36-stable/repodata/repomd.xml (IP: 104.26.9.21)
Error: Failed to download metadata for repo 'protonvpn-fedora-stable': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```
temporary solution using `dnf.. --releasever=35`

**Comment by rusticadam** [comment]
> ```shell
> ProtonVPN Fedora Stable repository                                             95  B/s | 162  B     00:01    
> Errors during downloading metadata for repository 'protonvpn-fedora-stable':
>   - Status code: 404 for https://repo.protonvpn.com/fedora-36-stable/repodata/repomd.xml (IP: 104.26.9.21)
> Error: Failed to download metadata for repo 'protonvpn-fedora-stable': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
> ```
> 
> temporary solution using `dnf.. --releasever=35`

Similar problem facing in all of my Fedora machines.

**Comment by iam-cult** [comment]
one other way you could get around it is using toolbox/distrobox (podman wrapper), and installing protonvpn in a fedora 35 container image.

**Comment by calexandru2018** [comment]
Hey @sbe-arg 

We only support released and stable distributions. Given that F36 is in not released to the public we currently don't support it.

**Comment by ElMoscaviador** [comment]
I am still having this issue on Fedora 35 :)

**Comment by govarthenan** [comment]
Hi @calexandru2018, since Fedora 36 is officially released now, when can we expect  repo for Fedora 36?

**Comment by Dyrimon** [comment]
Chiming in for this as well, this is the only one preventing me from upgrading.

**Comment by calexandru2018** [comment]
Fedora 36 has been introduced in beta.

**Comment by calexandru2018** [comment]
Fedora 36 is now also available in the stable channel
