### ISSUE TITLE
Doesn't connect to VPN server_Mint

### ISSUE THREAD

**Issue by christian179717** [ProtonVPN/linux-app#77]
Hello,
Proton VPN doesn't connect.
If I click connect the normal "connecting"-screen appears.
After about 75% is loaded a new window opens and ask for a password.:
![Unbenannt](https://user-images.githubusercontent.com/89655752/171684986-f67a9051-9e7a-4bc1-b156-ee310700809e.png)

If I click "OK" it takes some times and shows this window again.
If I insert the Proton VPN password the same happens.

I've already un- and reinstalled Proton VPN and deleted all .cache and .config files but nothing helps.

**Comment by MuhammedZakir** [comment]
This started happening _infrequently_ after updating. The password asked is OpenVPN config pass and not ProtonVPN account's. I have encountered this in both Linux CLI and iOS. However, unlike OP's, disconnecting and connecting again fixes this.

**Comment by draekko** [comment]
There is an ongoing outage and could be related to that, entering the openvpn password in my case does nothing then the dialog reappears.

**Comment by christian179717** [comment]
I did not set any OpenVPN config passwort.
What do you mean with disconnect and connect? What should I disconnect?

I did not do anything but it works now.

**Comment by MuhammedZakir** [comment]
> I did not set any OpenVPN config passwort.

When you try to connect to a ProtonVPN server and you don't use WireGuard, the apps use OpenVPN protocol to connect.

> What do you mean with disconnect and connect? What should I disconnect?

Simply click the "connecting" server to stop connecting, and click it again to start connecting.

**Comment by christian179717** [comment]
> > I did not set any OpenVPN config passwort.
>  
> When you try to connect to a ProtonVPN server and you don't use WireGuard, the apps use OpenVPN protocol to connect.

I still do not know which passwort you mean.

**Comment by christian179717** [comment]
Ok, thanks
