### ISSUE TITLE
No updates?

### ISSUE THREAD

**Issue by SM9CC** [ProtonVPN/linux-app#80]
Why has it been over a year since any updates have been made? Why the lack of care for paying customers that use Linux? I mean think about it, Linux users are more likely the demographic that is privacy-oriented, so it is absolutely backwards that the Windows app gets support and the Linux community is left in the dark.

Not to mention that we have been waiting years for a Proton Cloud client too, in its current state the cloud service is completely useless to me, I like Proton and its vision but I am afraid that it's just not worth me paying for Proton Unlimited and I shall be downgrading.

**Comment by calexandru2018** [comment]
Hey @SM9CC ,

Please do search before posting as I've even pinned the issue about the current situation https://github.com/ProtonVPN/linux-app/issues/76
